name: 'server redirect'
description: 'redirect github action server ssh for debug'
inputs:
  user_passwd:
    required: true
    description: 'set ssh password'
  npc_command:
    required: false
    description: 'npc run command in the nps web'
  npc_server:
    required: false
    description: 'nps address'
  npc_vkey:
    required: false
    description: 'npc vkey in the nps web'
  time_limit:
    required: false
    default: 600
    description: 'service time limit'
outputs:
  context:
    description: 'result output'
runs:
  using: node12
  main: 'dist/index.js'
