name: 'remote debug action'
description: 'ssh to remote or publish port to internet'
inputs:
  user_passwd:
    required: false
    description: 'set ssh password'
  time_limit:
    required: false
    default: 600
    description: 'service time limit'
outputs:
  context:
    description: 'ssh link address or just publish'
runs:
  using: 'node12'
  main: 'dist/main.js'
